name:Github Actions test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
    mvn_build:
        name: build
        runs-on: ubuntu-latest
        run: |
            echo "Build Project",
            mvn compile.
    mvn_test:
        name: test
        needs:mvn_build
        run: |
            echo "Run JUnit4",
            mvn test.
    